### ISSUE TITLE
allow custom substrate endpoint

### ISSUE THREAD

**Issue by brenzi** [polkawallet-io/polkawallet-flutter#10]
For general substrat-based projects it would be nice if the user could specify the RPC/WS address manually

**Comment by RomeroYang** [comment]
The polkawallet app was designed to be more user-friendly, so we simplified some functions.
Customed RPC/WS address will not be supported, developers can do that in the polkadot UI [polkadot-js/apps](https://github.com/polkadot-js/apps).

There are several substrat-based projects will be supported in this App in the future. And we are building this App to be multi-chain supported. You're welcome to contribute 😊.

**Comment by luatnd** [comment]
If my RPC endpoint is not on the supported list, can I open a pull request to add my RPC profile?
Does it take time?
