### ISSUE TITLE
 The page does not display the current position after opening a position

### ISSUE THREAD

**Issue by StrawberryFlavor** [polkawallet-io/polkawallet-flutter#102]
Steps:
1. In margin trading, buy long ETHUSD
2. Make Long than 0.01

Problem Description：
The page does not display the current position after opening a position

address: 5Coiddko324JRzZpr7yKMEhXhhmEEZS1PL3bW3zuydiiyj1G

**Comment by RomeroYang** [comment]
duplicated with #87
