### ISSUE TITLE
Only allowed to transfer aUSD between accounts on Laminar chain using Polkawallet but not using web Flow Exchange.

### ISSUE THREAD

**Issue by ltfschoen** [polkawallet-io/polkawallet-flutter#108]
**My Acala Mandala Address: 5DHcRs9udMCKtEmJEABY2HpECyTHHxgLL85pFFzN72SatAoQ**

If I go to https://flow.laminar.one/dashboard in web browser, and click "Transfer" aUSD, it only lets me transfer to "To Acala Account", but not to another account on the Laminar chain.

Whereas on mobile in Polkawallet I'm able to do that by importing that same account onto the Laminar Turbulence TC1 chain, it shows in "Assets" that I have a balance of 4 LAMI and 2750 aUSD. If I then click "aUSD", and then "Transfer", and choose a different address for "Send to Address" of 5DRech3cqa15p3m7rgd1AoLbm8erSbdddUJLo18ESvuUbscN, and enter an amount less than my balance and leaving enough to pay the tranfer fee (i.e. 2749.9989), and choose "aUSD" as Currency, and click "Make Transfer" , it will successfully transfer to another account on Laminar chain.

**Comment by RomeroYang** [comment]
so it's laminar flow-ex which not support token transfer, not any issue of Polkawallet.
