### ISSUE TITLE
跨链转账，只能给当前地址转账，不能选择其他地址

### ISSUE THREAD

**Issue by yidianshui** [polkawallet-io/polkawallet-flutter#109]
跨链转账，只能给当前地址转账，不能选择其他地址，ACA和LAMI互相跨链转账的时候，下面都有收款地址，可是却不能选择手动改地址，只能给默认当前地址跨链转账，
![3](https://user-images.githubusercontent.com/36132527/89192992-e848ee00-d5d7-11ea-95d4-e8a88af421ee.jpg)
![6](https://user-images.githubusercontent.com/36132527/89193080-06aee980-d5d8-11ea-9924-0936d009e4b3.jpg)

5EnWSikTvi8Y3S6vQ8TM3q5joFe8pCa4LjAbmEaXywwE6ioG

**Comment by RomeroYang** [comment]
是的，不能转给其他地址。
