### ISSUE TITLE
add some live data like block number

### ISSUE THREAD

**Issue by brenzi** [polkawallet-io/polkawallet-flutter#11]
Liveness can't be experienced right now with this app. The first thing I'd be looking for is increasing block number that I can match with some web block explorer

**Comment by RomeroYang** [comment]
Same reason with #10 , normal users of a wallet App doesn't  need informations like that.

**Comment by brenzi** [comment]
I disagree. As a user I need to be convinced that the data I see is recent and the connection is alive. This doesn't need to be very prominently showcased, but some kind of blockchain heartbeat would be desirable
