### ISSUE TITLE
钱包交易记录混乱！

### ISSUE THREAD

**Issue by wulin767** [polkawallet-io/polkawallet-flutter#114]
![QQ图片20200805164112](https://user-images.githubusercontent.com/39607939/89391467-d895ea80-d73a-11ea-8774-494fa6b07cda.jpg)
钱包交易记录混乱，首先DEX交易记录不按时间顺序。其次，同一钱包的不同账号混在一起，分不清楚是哪个账户交易的，不同交易账户的记录应该分开显示。

adress: 5GNqaqhFJvAJBuk9Vz6fziBMavZF9QfPZNX7X57u2zZeRNHy

**Comment by RomeroYang** [comment]
你用的哪个版本？
