### ISSUE TITLE
DOT, LDOT, RENBTC History section doesnt show IN/Received transactions

### ISSUE THREAD

**Issue by whoissatoshi** [polkawallet-io/polkawallet-flutter#115]
IOS app, Acala Mandala wallet, Asset section

DOT, LDOT, RENBTC **History section** doesnt show IN/Received transactions.
Only Sent/OUT transactions are displayed.

5F2FNhhVeG9bW4tP5te4a7asBJvSHQg31RzkoETLpUN161gV

**Comment by RomeroYang** [comment]
duplicated with #27
