### ISSUE TITLE
create account doesn't work on Xperia XZ1 compact on Oreo

### ISSUE THREAD

**Issue by brenzi** [polkawallet-io/polkawallet-flutter#13]
Polkawallet V0.6.0

1. Start app
2. create account. enter name +password
3. next step
4. "don't take screenshots"- > OK
5. Backup Mnemonic -> **No mnemonic appears!**

Importing account doesn't work neither. I can enter mnemonic, enter name and pwd. tapping "next step" does nothing.

Device:
Sony Xperia "lilac"

OS:
Android AOSP Oreo 8.0.0
without gapps

**Comment by RomeroYang** [comment]
Try [v0.6.2](https://github.com/polkawallet-io/polkawallet-flutter/releases/tag/v0.6.2-beta.2)
