### ISSUE TITLE
存入流动性时的黑屏问题

### ISSUE THREAD

**Issue by lijiahao666** [polkawallet-io/polkawallet-flutter#130]
存入流动性时，按gif中的步骤操作，就会发生黑屏现象。
![C5B897C5E2AA26EB2E5C452CD872C850](https://user-images.githubusercontent.com/57653984/89854161-bdf1c480-dbc5-11ea-9c21-d7af80aee6aa.gif)
地址：5Fe9ADtoyrnr2AVwxhxxrjNGyagTw2CMJvStEMbhDvWeKwHr

**Comment by RomeroYang** [comment]
同 #127 ，单独输入小数点解析错误。
