### ISSUE TITLE
切换不同主网后，所有收币地址都显示的波卡地址

### ISSUE THREAD

**Issue by jiangzhanwei** [polkawallet-io/polkawallet-flutter#139]
切换不同主网后，所有收币地址都显示的波卡地址，收款地址的弹框也是波卡的地址。
下面是我选的acala主网截图
![WechatIMG198](https://user-images.githubusercontent.com/19163404/90373878-30bade00-e0a5-11ea-909f-63c4a7ca9bcb.jpeg)
![WechatIMG199](https://user-images.githubusercontent.com/19163404/90373898-36b0bf00-e0a5-11ea-9b3c-1dc1c4e9aed4.jpeg)

acala 地址:
5FEp7o7MW6m5Tx6G5pGeto9ZQpfHKePVREVkmDxV58ZoPg6H

**Comment by RomeroYang** [comment]
你是不是在设置里设置了地址格式？

**Comment by jiangzhanwei** [comment]
> 你是不是在设置里设置了地址格式？

哦哦 是我的配置问题 打扰啦
