### ISSUE TITLE
0.9.4-beta.1，自助借贷，存入和取出操作屏幕显示问题

### ISSUE THREAD

**Issue by yidianshui** [polkawallet-io/polkawallet-flutter#140]
0.9.4-beta.1，安卓，自助借贷，存入和取出操作屏幕显示问题，存入和取出分别测试输入小数点.会跳到灰色页面，下面点发送交易才会跳转到发送交易页面。而且输入小数点也能正常交易，ACA手续费正常扣款。
![22](https://user-images.githubusercontent.com/36132527/90474244-6fa96c00-e157-11ea-83fe-22c115e5aae2.jpg)
5EnWSikTvi8Y3S6vQ8TM3q5joFe8pCa4LjAbmEaXywwE6ioG

**Comment by RomeroYang** [comment]
重复 #127
