### ISSUE TITLE
When storing liquidity, the wrong character causes a BUG

### ISSUE THREAD

**Issue by StrawberryFlavor** [polkawallet-io/polkawallet-flutter#141]
Steps：
1. When depositing liquidity, enter the "." character on both sides of the exchange amount
2. Click to deposit liquidity

Problem Description：
After the signature is sent, an error will be reported. At this point, click the back button and the APP will go black

![image](https://user-images.githubusercontent.com/28721839/90471234-3cafaa00-e150-11ea-8da4-d891daab3920.png)
![image](https://user-images.githubusercontent.com/28721839/90471252-476a3f00-e150-11ea-96b6-562798e52557.png)

Address : 5Coiddko324JRzZpr7yKMEhXhhmEEZS1PL3bW3zuydiiyj1G

**Comment by RomeroYang** [comment]
duplicated #128
