### ISSUE TITLE
An interface error caused by a character in a debit or credit

### ISSUE THREAD

**Issue by StrawberryFlavor** [polkawallet-io/polkawallet-flutter#145]
Steps:
1. Create a pledge loan
2. Enter "." loan
3. Enter "." to lend stablecoin

Problem Description:
There will be interface problems

![image](https://user-images.githubusercontent.com/28721839/90483855-f9613580-e167-11ea-8330-9c8c3fc060d8.png)

Address: 5Coiddko324JRzZpr7yKMEhXhhmEEZS1PL3bW3zuydiiyj1G

**Comment by RomeroYang** [comment]
duplicated #127
