### ISSUE TITLE
A BUG in the interface caused by characters during credit and deposit

### ISSUE THREAD

**Issue by StrawberryFlavor** [polkawallet-io/polkawallet-flutter#146]
Steps:
1. In self-help lending, continue to deposit the corresponding mortgage
2. Enter input “.”

Problem Description:
![image](https://user-images.githubusercontent.com/28721839/90487635-51e70180-e16d-11ea-9245-726479edc8f0.png)

Address: 5Coiddko324JRzZpr7yKMEhXhhmEEZS1PL3bW3zuydiiyj1G

**Comment by RomeroYang** [comment]
duplicated #127
