### ISSUE TITLE
When using the QR code scan, open the non-address QR code scan from the album, and the scanning program will get stuck

### ISSUE THREAD

**Issue by YouAreMMorGG** [polkawallet-io/polkawallet-flutter#147]
If you open a QR code or other photo from the album that is not an address, the scanner will get stuck

My Address : 5EebcYK8iR1zstXZiAF7uyVxQrKebZJaBKW9ow5GtHwve8AT

**Comment by RomeroYang** [comment]
nmsl

**Comment by YouAreMMorGG** [comment]
> nmsl
what is it nmsl ??

**Comment by kennbmondo** [comment]
I think it stands for “Ni Ma Si Le”
