### ISSUE TITLE
存款盈利板块，操作出现黑屏。

### ISSUE THREAD

**Issue by yidianshui** [polkawallet-io/polkawallet-flutter#148]
存入流动性，Dot输入<.>。ausd输入<.>按返回键，或者按键盘下箭头，出现黑屏闪退。
![IMG_20200818_223825](https://user-images.githubusercontent.com/36132527/90527016-a6a56f00-e1a3-11ea-9f1c-4f117f0674d7.jpg)
![Screenshot_20200818-223951](https://user-images.githubusercontent.com/36132527/90527122-c5a40100-e1a3-11ea-9943-042c604da45c.jpg)

5EnWSikTvi8Y3S6vQ8TM3q5joFe8pCa4LjAbmEaXywwE6ioG

**Comment by RomeroYang** [comment]
重复 #128
