### ISSUE TITLE
L-DOT质押提取，无法输入光标

### ISSUE THREAD

**Issue by yidianshui** [polkawallet-io/polkawallet-flutter#149]
生成L-DOT，打开界面准备操作，LDOT自动输入0.00，并且无法插入光标。提取DOT，打开界面准备操作，DOT自动输入0.00，并且无插入光标。
![IMG_20200818_223449](https://user-images.githubusercontent.com/36132527/90526589-2979fa00-e1a3-11ea-97b2-dbe07c0135b5.jpg)
![IMG_20200818_223430](https://user-images.githubusercontent.com/36132527/90526615-326acb80-e1a3-11ea-96eb-cd3fbe434bce.jpg)

5EnWSikTvi8Y3S6vQ8TM3q5joFe8pCa4LjAbmEaXywwE6ioG

**Comment by RomeroYang** [comment]
该操作仅支持输入左侧支付数量，右侧数值根据系统状态计算生成。
