### ISSUE TITLE
返回的hash 和浏览器查到的不一样 

### ISSUE THREAD

**Issue by mghnmtt** [polkawallet-io/polkawallet-flutter#152]
{"path":"uid=3;account.sendTx","data":{"hash":"0x946e012067810f6419bdf7f22dc250b1071dc298d9070a3c44b7de7f2efffd88"}}

请问是返回错误么

**Comment by mghnmtt** [comment]
执行sendTx 返回的hash 和实际浏览器查到的不一样

**Comment by RomeroYang** [comment]
> 执行sendTx 返回的hash 和实际浏览器查到的不一样

什么场景，浏览器链接

**Comment by RomeroYang** [comment]
tx hash是有问题，#152 修复了。

账户存活余额是波卡的机制设计，用来节省链上存储。

顺便问一下你是基于polkawallet做什么项目？
我们正在做 [https://github.com/polkawallet-io/sdk](https://github.com/polkawallet-io/sdk), 希望能够更加方便的支持各种substrate项目接入，如果有什么需求都可以提，我们尽量把做得功能通用一些。

**Comment by mghnmtt** [comment]
感谢大佬指导和提供的帮助  目前是在钱包中支持DOT转账功能  后面会接入一些Dapp
