### ISSUE TITLE
APP创建新账户没有助记词生成

### ISSUE THREAD

**Issue by yidianshui** [polkawallet-io/polkawallet-flutter#180]
安卓APP钱包，助记词无法生成。已经升级到最新版本
![Screenshot_20201031-212831](https://user-images.githubusercontent.com/36132527/97780541-43cb4d80-1bc0-11eb-8e65-3641d48a1933.jpg)
![Screenshot_20201031-212836](https://user-images.githubusercontent.com/36132527/97780548-48900180-1bc0-11eb-93d5-7648ca26ec05.jpg)

**Comment by RomeroYang** [comment]
部分安卓机型可能出现不适配的情况。
