### ISSUE TITLE
acala 的存款盈利功能异常

### ISSUE THREAD

**Issue by qklsczn** [polkawallet-io/polkawallet-flutter#182]
在acala中的存款盈利功能，选择存入ausd-xbtc ausd-renbtc 时，当先输入第一个币种ausd数量时，后面币种数量不会自动填充对应数量，会提示格式错误。但是先填第二个币种数量时就会自动填充第一个币种数量。

5F9iD4xj9WyAiYgfzSMSUfWwnPTx7ePpGVU9Qdo2jTKSb4vc

**Comment by qklsczn** [comment]
> 在acala中的存款盈利功能，选择存入ausd-xbtc ausd-renbtc 时，当先输入第一个币种ausd数量时，后面币种数量不会自动填充对应数量，会提示格式错误。但是先填第二个币种数量时就会自动填充第一个币种数量。

> 此问题出现在polkawallet安卓版钱包内，使用小米9以及小米6均出现同样问题
> 5F9iD4xj9WyAiYgfzSMSUfWwnPTx7ePpGVU9Qdo2jTKSb4vc

**Comment by RomeroYang** [comment]
感谢反馈，自动填充数量太小显示格式错误，我们会在下个版本修复。
