### ISSUE TITLE
flow交易平台，显示错误，不能自能填充正确的兑换数量

### ISSUE THREAD

**Issue by yidianshui** [polkawallet-io/polkawallet-flutter#183]
flow交易平台，显示错误，不能智能填充正确的兑换数量，使用AUSD兑换fjpy，汇率1:104..7。在使用AUSD兑换FCAD时候，不能自能变成FCAD的汇率，还是显示fjpy的汇率104.7
![IMG_20201031_231558](https://user-images.githubusercontent.com/36132527/97783018-edfea180-1bcf-11eb-892d-3a84983e42ab.jpg)
![IMG_20201031_231628](https://user-images.githubusercontent.com/36132527/97783021-f525af80-1bcf-11eb-8c72-22a20b35babb.jpg)

**Comment by StrawberryFlavor** [comment]
laminar暂时没更新，请使用Acala平台操作
