### ISSUE TITLE
Acala稳定币平台BUG

### ISSUE THREAD

**Issue by haifengcui0529** [polkawallet-io/polkawallet-flutter#184]
操作自助借贷，存款盈利总是偶尔出现报错：cdpEngine BelowRequiredCollateralRatio

**Comment by haifengcui0529** [comment]
调用 honzon . adjustLoan 详情{" colleterals ":"55":' debits ":"250"}
反馈问题如上，希望能对交互起到帮助，5Eq7q9pqm1WxoD7M2sHCj7xp3ubnryygGRPAq4ECwfuxAbhw

**Comment by RomeroYang** [comment]
在自助借贷中 BelowRequiredCollateralRatio 提示抵押物低于所需的抵押率，所以交易失败。
假如该交易执行成功，那么贷款会因为抵押率过低而被立即清算掉。
