### ISSUE TITLE
Use json to import the account in the Polka wallet APP No prompt

### ISSUE THREAD

**Issue by atinst** [polkawallet-io/polkawallet-flutter#185]
![199](https://user-images.githubusercontent.com/32417799/97800817-489d0980-1c73-11eb-88ff-3e1e6ebb42fb.jpg)
Use json to import the account in the Polka wallet APP. When you click the next step, a loading prompt will appear. After waiting for a few seconds, the prompt will disappear. After it disappears, you will stay on the account import page. I am confused. Because I don't know whether the account is imported successfully, there is no prompt when the interface stays here.

**Comment by atinst** [comment]
I think it should remind me whether my account has been imported successfully. If it has been successful, please jump to the homepage instead of staying here.

**Comment by atinst** [comment]
When the password is wrong, it will pop up a prompt box. When you click to confirm, the loading floating layer still exists. At this time, you can no longer perform any operations. You can only kill the process and start over from the beginning.

**Comment by atinst** [comment]
At present, you will not get any prompts if you successfully import the account through json, and the interface will not jump to the homepage. If the password is wrong, you will be stuck on this interface, you can only kill the program and start over.

**Comment by atinst** [comment]
Acala address：5HnJRCcbFaTjaYhmhTiNavSStkxRAmeX2EiEJq2vSnN5Q4TJ

**Comment by atinst** [comment]
![7](https://user-images.githubusercontent.com/32417799/97801172-df6ac580-1c75-11eb-9d98-4afdf195abff.png)

**Comment by RomeroYang** [comment]
Thanks for your report, this bug will occur while App is not connect to remote node. We will fix it later.

**Comment by atinst** [comment]
> Thanks for your report, this bug will occur while App is not connect to remote node. We will fix it later.

不，并不是这样的，我很确定在首页节点已经成功连接，我说明的这个问题是在节点成功连接时发生的。
当你使用JSON方式导入账户时 如果一切正确 等待加载中那个浮层消失后 你会停留在导入账户下一步这个界面 你并不会得到导入成功这种提示 你也不会被跳转到首页 告诉你账户已经导入了  当你重复点击下一步时 它会提示你账户已经存在。

如果你密码输入错误了 它会提示你密码错误 当你点击确定后 加载中这个浮层会一直显示一直在转圈 除非你杀掉这个程序 否则就死在这个界面了。

以上问题均是在已经成功连接节点的情况下发生的，请您尝试复现，谢谢。
