### ISSUE TITLE
Thanks for your report, this bug will occur while App is not connect to remote node. We will fix it later.

### ISSUE THREAD

**Issue by atinst** [polkawallet-io/polkawallet-flutter#186]
Thanks for your report, this bug will occur while App is not connect to remote node. We will fix it later.

_Originally posted by @RomeroYang in https://github.com/polkawallet-io/polkawallet-flutter/issues/185#issuecomment-720225290_

不，并不是这样的，我很确定在首页节点已经成功连接，我说明的这个问题是在节点成功连接时发生的。
当你使用JSON方式导入账户时 如果一切正确 等待加载中那个浮层消失后 你会停留在导入账户下一步这个界面 你并不会得到导入成功这种提示 你也不会被跳转到首页 告诉你账户已经导入了 当你重复点击下一步时 它会提示你账户已经存在。

如果你密码输入错误了 它会提示你密码错误 当你点击确定后 加载中这个浮层会一直显示一直在转圈 除非你杀掉这个程序 否则就死在这个界面了。

以上问题均是在已经成功连接节点的情况下发生的，请您尝试复现，谢谢。

**Comment by RomeroYang** [comment]
It also occurs while the device is not support biometrics, it will be fixed in next release.😊
