### ISSUE TITLE
资金池充足，但是提取DOT时提示资金池余额不足，导致无法提取DOT

### ISSUE THREAD

**Issue by hijonehi** [polkawallet-io/polkawallet-flutter#191]
在以立即取回方式提取DOT时，资金池显示充足，账号余额也足够，但是点击提取时，提示资金池余额不足，导致无法提取DOT

![image](https://user-images.githubusercontent.com/61875854/97976926-5931b900-1e06-11eb-9fae-bc80f56c7daf.png)

5HnB6WGwGFZU87ViXYhVxxPEKS1K8r2QTQnvSPg9tWqVApxY

**Comment by StrawberryFlavor** [comment]
The new version has been fixed
