### ISSUE TITLE
Wallet issues!

### ISSUE THREAD

**Issue by elvinvalentin** [polkawallet-io/polkawallet-flutter#208]
Hi the reason I'm writing is because since Sunday I haven't been able to log into the wallet when I click on the icon it goes into the app but the screen right away turns black if you can write back with guidance on how to solve the issue will b greatly appreciated thank you and be safe.

**Comment by RomeroYang** [comment]
The black screen was caused by a mishandled data upgrade bug，you can stay on the black screen and wait for a while, the app will turn normal while connected to remote node.

And the bug was fixed in latest release: v1.1.5-beta.1, sorry for the inconvenience.
