### ISSUE TITLE
No log out

### ISSUE THREAD

**Issue by vryadly** [polkawallet-io/polkawallet-flutter#209]
Android, v1.1.5-beta.1

When I press back arrow at the bottom left of the Android screen, the wallet asks me "Do you want to exit the App?"

If I press OK, it redirects me to the phone's main screen. But when I press the square at the bottom right of the Android screen, Polkawallet is still in the list of the open apps and I can reenter it without password. 

I couldn't find any other way to log out.

**Comment by RomeroYang** [comment]
There is no log out.

This wallet was designed to be accessible without password. Password is only required when signing and sending a Tx.
If you have several different accounts in the wallet, you will have several different passwords for each account. Just behaving like the Polkadot official wallet: [polkadot-js chrome extension](https://github.com/polkadot-js/extension).

We will consider to make the wallet become accessible only with a password. Thanks for your feedback.

**Comment by vryadly** [comment]
Thank you for the answer, I understand.

Still, notwithstanding, when it's in the list of open apps after I've exited it, it looks like a bug.

**Comment by RomeroYang** [comment]
If you press the square menu button of Android, it will show you a list of apps that you have opened, not open apps. Exited apps will not disappear from this list automatically.

**Comment by vryadly** [comment]
Sorry, but it's just not true. All exited apps do disappear from the list, except for the wallet

UPD corrected - I've found a couple of apps (both are book readers) that behave just like yours - switch to the main screen instead of exit and stay on the list. Still, in my opinion, it looks misguiding. And I couldn't find any app that shows the thumbnail with the exit dialog.

Anyways, the ticket is closed.

**Comment by vryadly** [comment]
Probably, you mean that they don't disappear when you log out. Which is true, but in case of Polkawallet it's not a log out, because, as you've said, there's no log out in Polkawallet, 'cause there's no log in.
