### ISSUE TITLE
import account freezes on SM G800F (Android 6.0.1)

### ISSUE THREAD

**Issue by brenzi** [polkawallet-io/polkawallet-flutter#34]
I've built polkawallet from `develop` branch today 53e45771312594be905bd29979bb053c2e91554f

polkawallet starts on SM G800F and 
1. choose "import account"
2. enter mnemonic
3. enter username & passwd twice
4. hit "next step"
5. app spins for a while, then I'm back at the choice "Create Account" / "Import Account"

On AVD Pixel2 Oreo it worked. But not on the stated device

**Comment by RomeroYang** [comment]
`sr25519` account generation will fail if the webview on the device doesn't support WASM.

I've added some error info and solution suggestion popups when that happens. 
You can try it in the latest `develop` branch. @brenzi

**Comment by brenzi** [comment]
solved. tested with e8c100b6dc43419233b02948852aa6ddd33307d5
