### ISSUE TITLE
import account key broken

### ISSUE THREAD

**Issue by brenzi** [polkawallet-io/polkawallet-flutter#40]
running on AVD Pixel2 x86 emulator
tested with recent develop branch 737fb150fa6517b2f78835260c8a13ef009a45c1

1. import key
2. enter mnemonic
3. enter label and password
4. app tells me that "This device doesn not support encrypt sr25519....."

OK, so I try the suggestion
1. import key
2. select advanced options -> Encrypt type ed25519
2. enter mnemonic
3. enter label and password
4. app tells me that "This device doesn not support encrypt sr25519....."

same result.

creating a fresh sr25519 account works

moreover, I find it confusing that you use the word "encrypt" for a key that is only meant for signing. May I suggest "account type" or "key type"?

**Comment by RomeroYang** [comment]
It works well in my env, maybe rebuild the js file will help.
And Thanks for the suggestion, I will use "key type" instead.

**Comment by brenzi** [comment]
I only built the js_service_encointer but forgot to rebuild js_service_kusama as well. I'll check again
