### ISSUE TITLE
Can I use this to connect my server?

### ISSUE THREAD

**Issue by zhangtianai** [polkawallet-io/polkawallet-flutter#46]

**Comment by RomeroYang** [comment]
Customized endpoint is not supported.

If you want to connect your substrate test node you can use [polkadot-js/apps](https://polkadot.js.org/apps/#/settings).

If you want to add your substrate-based project into this app, then you need some coding like the AcalaNetwork part of this app.

**Comment by RomeroYang** [comment]
and here: https://github.com/polkawallet-io/polkawallet-flutter/issues/10

**Comment by luatnd** [comment]
> If you want to add your substrate-based project into this app, then you need some coding like the AcalaNetwork part of this app.

Please publish a document, so many apps need this, if polkawallet supports this, it's might be the most popular wallet for substrate-based users
