### ISSUE TITLE
Menu includes "Create Account" but not "Import Account"

### ISSUE THREAD

**Issue by ltfschoen** [polkawallet-io/polkawallet-flutter#47]
In the app, if I click the hamburger menu icon, it only shows an option "Create Account", which takes me to a screen where it displays "Create Account" option again plus "Import Account" option.

It would be better for the hamburger menu to include both "Create Account" and "Import Account" and clicking either of those taking you straight to the relevant page

**Comment by RomeroYang** [comment]
The drawerMenu was deprecated in `develop` branch, for now the path is "hamburger menu" -> "network select page" -> "create & import account page".
