### ISSUE TITLE
Gradle Wrapper missing distributionSha256Sum

### ISSUE THREAD

**Issue by jiangfuyao** [polkawallet-io/polkawallet-flutter#52]
issue for F-droid: https://gitlab.com/fdroid/rfp/-/issues/1407#note_372473129

help: https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:verification

*gradle/wrapper/gradle-wrapper.properties* is missing [distributionSha256Sum](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:verification), unverified gradle download! Here is an example of how to fix this:

```properties
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip
distributionSha256Sum=027fdd265d277bae65a0d349b6b8da02135b0b8e14ba891e26281fa877fe37a2
```

**Comment by RomeroYang** [comment]
fixed https://github.com/polkawallet-io/polkawallet-flutter/commit/eee13742635089d4199a1e328d20b9d11e7bcd67
