### ISSUE TITLE
withdrawUnbonded/unbonding? 

### ISSUE THREAD

**Issue by joshua-mir** [polkawallet-io/polkawallet-flutter#57]
does Polkawallet have a method to call the staking.withdrawUnbonded extrinsic? I've seen several users run into the issue that they cannot actually unbond once their balance is redeemable.

It may just be the case that I haven't noticed it yet, apologies in that case.

**Comment by RomeroYang** [comment]
If you do have withdrable unbonded token, you will see a small icon button on top of the unbonded value, just click the button to withdraw.

**Comment by joshua-mir** [comment]
thanks!
