### ISSUE TITLE
Polkawallet自助借贷完成后资产却没有增加

### ISSUE THREAD

**Issue by ottomu1314** [polkawallet-io/polkawallet-flutter#65]
在自助借贷中存入小额0.059LDOT借出0.789aUSD成功后，在资产列表中相关资产数额显示并没有增减。经过三次不同账号测试后都是如此，请知悉。5E7b8rmiWDahDN6ZUNuyqmSirQsPj8PAMZ9CYMaURCjcDEqn

**Comment by RomeroYang** [comment]
完善功能，需要监听广播时间判断发送完成的交易是否成功。
