### ISSUE TITLE
aUSD兑换DOT成功后相应资产无增减

### ISSUE THREAD

**Issue by ottomu1314** [polkawallet-io/polkawallet-flutter#71]
用10aUSD成功兑换0.05DOT后（交易地址如下5CFDUhg23rkMJuTA6KnoTHnYVfv6fSBQzNjZi7L7TZkSdmAd），交易记录显示兑换完成成功，但资产界面相应资产却不能同步增减，多次刷新后一直没变化。

奖励
5E7b8rmiWDahDN6ZUNuyqmSirQsPj8PAMZ9CYMaURCjcDEqn

**Comment by RomeroYang** [comment]
duplicated with #65
