### ISSUE TITLE
L-DOT质押/提取，（提取DOT）输入密码这一页，显示错误

### ISSUE THREAD

**Issue by yidianshui** [polkawallet-io/polkawallet-flutter#72]
L-DOT质押/提取，（提取DOT）操作的时候，点提取DOT，在输入密码这一步时候，最上端显示的是（生成L-DOT）而不是提取DOT，在交易完成时候，下一页，又是正常显示（提取DOT）。这里显示错误，请尽快修改，谢谢。
图1，操作前，显示提取DOT.
![111](https://user-images.githubusercontent.com/36132527/89056335-6fa32100-d38e-11ea-9bd5-2076fe49ad12.jpg)

图2，点提取DOT，准备输入密码这一页，上面显示错误，显示生成LDOT，
![22222](https://user-images.githubusercontent.com/36132527/89056378-821d5a80-d38e-11ea-8c76-018547e2e9c4.jpg)

图3，输入密码操作完，正常显示，提取DOT，
![3333](https://user-images.githubusercontent.com/36132527/89056619-e3452e00-d38e-11ea-898c-797ac43838b2.jpg)

5EnWSikTvi8Y3S6vQ8TM3q5joFe8pCa4LjAbmEaXywwE6ioG

**Comment by RomeroYang** [comment]
duplicated with #70
