### ISSUE TITLE
自助借贷，低于借贷1U以下的。借款失败

### ISSUE THREAD

**Issue by yidianshui** [polkawallet-io/polkawallet-flutter#73]
自助借贷，创建质押借贷DOT，低于借贷1U以下的。借款不会成功。但是操作完成以后，每次都会正常扣Aca手续费，并且每次借贷低于1U的交易记录也有，每次也提示交易打包已完成。操作地址，5FnsR3vEGLjodK5ULVZK4o5CioG5PSfg5F5M4UxZuAXY4KMu
图1，是借贷以前的钱包显示。
![1](https://user-images.githubusercontent.com/36132527/89054559-9875e700-d38b-11ea-894d-7a8261aa0293.jpg)

图2，输入0.9U。准备借贷。
![2](https://user-images.githubusercontent.com/36132527/89055137-82b4f180-d38c-11ea-9f8f-f1c3b343fa94.jpg)

图3，借贷结果。不成功。
![3](https://user-images.githubusercontent.com/36132527/89055079-69ac4080-d38c-11ea-9b40-126471fcd68e.jpg)

图4，借贷后钱包最后显示。
![4](https://user-images.githubusercontent.com/36132527/89055103-76309900-d38c-11ea-9953-92d6b6d22b37.jpg)

5EnWSikTvi8Y3S6vQ8TM3q5joFe8pCa4LjAbmEaXywwE6ioG

**Comment by RomeroYang** [comment]
duplicated with #65
