### ISSUE TITLE
自助借贷，用DoT.，XBTC，LDOT，RenBtc借款后，不能全额还贷

### ISSUE THREAD

**Issue by yidianshui** [polkawallet-io/polkawallet-flutter#77]
自助借贷板块，用DoT.，XBTC，LDOT，RenBtc借款后，不能全额还贷，多次拆分还贷，也能少量还款，但是不能一次全额性还贷。并且每次收费正常收取，交易记录也有。操作钱包地址。5EnWSikTvi8Y3S6vQ8TM3q5joFe8pCa4LjAbmEaXywwE6ioG
图1，准备借贷1555.1
![1](https://user-images.githubusercontent.com/36132527/89050028-b7bd4600-d384-11ea-8b39-056e0762a197.jpg)

图2，借贷成功。债务由1555,1
![2](https://user-images.githubusercontent.com/36132527/89050270-1aaedd00-d385-11ea-83d3-be902b95742b.jpg)

图3，显示还贷已成功，但实际没有还贷。
![3](https://user-images.githubusercontent.com/36132527/89050368-3ca85f80-d385-11ea-991a-0e6363938926.jpg)

图4，连续两次还贷交易记录、
![4](https://user-images.githubusercontent.com/36132527/89050389-4762f480-d385-11ea-9ff0-cd4ee74082ad.jpg)

图5，还贷结果。还是显示1555,11
![5](https://user-images.githubusercontent.com/36132527/89050503-6ceffe00-d385-11ea-8da2-d48d0ef76e21.jpg)

5EnWSikTvi8Y3S6vQ8TM3q5joFe8pCa4LjAbmEaXywwE6ioG

**Comment by RomeroYang** [comment]
duplicated with #75
