### ISSUE TITLE
自助借贷板块，创建质押借贷完后，还贷用小数点完成

### ISSUE THREAD

**Issue by yidianshui** [polkawallet-io/polkawallet-flutter#81]
自助借贷板块，创建质押借贷完后，在还贷的时候，尽然输入一个小数点，就可以全额还贷了，比如我借贷了156.2U，输入一个小数点还贷完成后，看交易记录，也是显示还贷156.2U，手续费也正常收取
5EnWSikTvi8Y3S6vQ8TM3q5joFe8pCa4LjAbmEaXywwE6ioG

**Comment by wangjj9219** [comment]
输入框bug，小数点表示max， 其实你的aUSD也少了156.2U
