### ISSUE TITLE
交易记录错误显示

### ISSUE THREAD

**Issue by yidianshui** [polkawallet-io/polkawallet-flutter#82]
生成L-DOT，DOT支付数量0.001.LDOT0.010 交易成功后，交易记录错误显示。显示0.010LDOT。0.01DOT。钱包币的出入是正确的。经过测试，提取DOT，输入的数量和交易记录相符,操作钱包地址。5FnsR3vEGLjodK5ULVZK4o5CioG5PSfg5F5M4UxZuAXY4KMu
图1，是操作以前，输入的数字。
![1](https://user-images.githubusercontent.com/36132527/89058455-e857ac80-d391-11ea-9e3f-de43180d60f5.jpg)

图2、是交易完成后，交易记录， 
![2](https://user-images.githubusercontent.com/36132527/89058522-02918a80-d392-11ea-8d20-93c67a49a47c.jpg)

5EnWSikTvi8Y3S6vQ8TM3q5joFe8pCa4LjAbmEaXywwE6ioG

**Comment by RomeroYang** [comment]
duplicated with #68

**Comment by yidianshui** [comment]
> 与[＃65](https://github.com/polkawallet-io/polkawallet-flutter/issues/65)重复[](https://github.com/polkawallet-io/polkawallet-flutter/issues/65)

这怎么能和65问题一样?他是成功交易完成以后资产没有增减，我这个问题这是正常交易完成后。资产也有增减，是交易记录错误显示啊。这分明是两个问题啊。
