### ISSUE TITLE
Faucet Of Acala Executed But Not Recived Test Token

### ISSUE THREAD

**Issue by theman1** [polkawallet-io/polkawallet-flutter#88]
Hey During Acala Mandal festival i tried faucet but trx exchted but test token not appeared in wallet. Sharing address also for Bug bounty.

5FA4ftYoARGqpdbPWWohXyjGcWSjTRyYKCsFrQiRuSVY9Spm

**Comment by RomeroYang** [comment]
Maybe it's an issue of Acala faucet service, not a problem of Polkawallet.
