### ISSUE TITLE
 Withdrawal of collateral can leave a small amount

### ISSUE THREAD

**Issue by StrawberryFlavor** [polkawallet-io/polkawallet-flutter#92]
When Self Serviced Loan retrieves the collateral, it can keep a relatively small part in it, which may cause problems when taking it out on the web

address: 5Coiddko324JRzZpr7yKMEhXhhmEEZS1PL3bW3zuydiiyj1G

**Comment by RomeroYang** [comment]
should withdraw all collateral if user input amount has little difference with max amount.
