### ISSUE TITLE
The amount of collateral shows a calculation error

### ISSUE THREAD

**Issue by StrawberryFlavor** [polkawallet-io/polkawallet-flutter#93]
![image](https://user-images.githubusercontent.com/28721839/89147811-654d7680-d58a-11ea-9df4-00bd144d6dc4.png)

It has actually been taken out, and only a very small part of the collateral remains
It may be due to the problem that the amount is too small, resulting in a calculation error when calculating the remaining collateral

Current actual collateral: 0.0000000064
Page displays collateral: 1.003

address: 5Coiddko324JRzZpr7yKMEhXhhmEEZS1PL3bW3zuydiiyj1G

**Comment by RomeroYang** [comment]
#92
