### ISSUE TITLE
在Flow交易平台中，合成资产，获取不到汇率

### ISSUE THREAD

**Issue by StrawberryFlavor** [polkawallet-io/polkawallet-flutter#97]
操作步骤：
1. 进入Flow操作平台
2. 进行合成资产

问题描述：不显示aUSD 和 FOIL的汇率情况
![image](https://user-images.githubusercontent.com/28721839/89154118-dc8a0700-d598-11ea-999f-508ceb3dcf9d.png)

address: 5Coiddko324JRzZpr7yKMEhXhhmEEZS1PL3bW3zuydiiyj1G

**Comment by RomeroYang** [comment]
交易池不支持兑换
